name: rxservice
description: A simple reactive service library for Dart and Flutter. Use in 
  conjuction with get_it and StreamBuilder for a complete state management 
  solution.
version: 0.1.0
repository: https://github.com/gekkotadev/rxservice

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  rxdart: ^0.27.7
  # path: ^1.8.0

dev_dependencies:
  get_it: ^7.6.0
  lints: ^2.0.0
  test: ^1.21.0
