name: rxservice
description: A simple reactive service library for Dart and Flutter. Use with StreamBuilder for Flutter apps.
version: 0.6.0
repository: https://github.com/gekkotadev/rxservice

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
  # path: ^1.8.0

dev_dependencies:
  equatable: ^2.0.5
  get_it: ^7.6.0
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  rxs: ">=0.2.0 <1.0.0"
