name: rxservice
description: A simple reactive service library for Dart and Flutter. Use in 
  conjuction with get_it and StreamBuilder for a complete state management 
  solution.
version: 0.5.0
repository: https://github.com/gekkotadev/rxservice

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
  # path: ^1.8.0

dev_dependencies:
  get_it: ^7.6.0
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  rxs: ^0.0.1
